Spice/Areas/Customer/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Spice.Data;
using Spice.Models;
using Spice.Models.ViewModels;
using Spice.Utility;

namespace Spice.Areas.Customer.Controllers {
    [Area ("Customer")]
    public class CartController : Controller {
        private readonly ApplicationDbContext _db;
        private readonly IEmailSender _emailSender;

        private static Random random = new Random();
        public static string RandomString(int length)
        {
            const string chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            return new string(Enumerable.Repeat(chars, length)
              .Select(s => s[random.Next(s.Length)]).ToArray());
        }

        [BindProperty]
        public OrderDetailsCart detailCart { get; set; }

        public CartController (ApplicationDbContext db, IEmailSender emailSender) {
            _db = db;
            _emailSender = emailSender;
        }

        public async Task<IActionResult> Index () {

            detailCart = new OrderDetailsCart () {
                OrderHeader = new Models.OrderHeader ()
            };

            detailCart.OrderHeader.OrderTotal = 0;

            var claimsIdentity = (ClaimsIdentity) User.Identity;
            var claim = claimsIdentity.FindFirst (ClaimTypes.NameIdentifier);

            var cart = _db.ShoppingCart.Where (c => c.ApplicationUserId == claim.Value);
            if (cart != null) {
                detailCart.listCart = cart.ToList ();
            }

            foreach (var list in detailCart.listCart) {
                list.MenuItem = await _db.MenuItem.FirstOrDefaultAsync (m => m.Id == list.MenuItemId);
                detailCart.OrderHeader.OrderTotal = detailCart.OrderHeader.OrderTotal + (list.MenuItem.Price * list.Count);
                list.MenuItem.Description = SD.ConvertToRawHtml (list.MenuItem.Description);
                if (list.MenuItem.Description.Length > 100) {
                    list.MenuItem.Description = list.MenuItem.Description.Substring (0, 99) + "...";
                }
            }
            detailCart.OrderHeader.OrderTotalOriginal = detailCart.OrderHeader.OrderTotal;

            if (HttpContext.Session.GetString (SD.ssCouponCode) != null) {
                detailCart.OrderHeader.CouponCode = HttpContext.Session.GetString (SD.ssCouponCode);
                var couponFromDb = await _db.Coupon.Where (c => c.Name.ToLower () == detailCart.OrderHeader.CouponCode.ToLower ()).FirstOrDefaultAsync ();
                detailCart.OrderHeader.OrderTotal = SD.DiscountedPrice (couponFromDb, detailCart.OrderHeader.OrderTotalOriginal);
            }

            return View (detailCart);

        }

        public async Task<IActionResult> Summary () {

            detailCart = new OrderDetailsCart () {
                OrderHeader = new Models.OrderHeader ()
            };

            detailCart.OrderHeader.OrderTotal = 0;

            var claimsIdentity = (ClaimsIdentity) User.Identity;
            var claim = claimsIdentity.FindFirst (ClaimTypes.NameIdentifier);
            ApplicationUser applicationUser = await _db.ApplicationUser.Where (c => c.Id == claim.Value).FirstOrDefaultAsync ();
            var cart = _db.ShoppingCart.Where (c => c.ApplicationUserId == claim.Value);
            if (cart != null) {
                detailCart.listCart = cart.ToList ();
            }

            foreach (var list in detailCart.listCart) {
                list.MenuItem = await _db.MenuItem.FirstOrDefaultAsync (m => m.Id == list.MenuItemId);
                detailCart.OrderHeader.OrderTotal = detailCart.OrderHeader.OrderTotal + (list.MenuItem.Price * list.Count);

            }
            detailCart.OrderHeader.OrderTotalOriginal = detailCart.OrderHeader.OrderTotal;
            detailCart.OrderHeader.PickupName = applicationUser.Name;
            detailCart.OrderHeader.PhoneNumber = applicationUser.PhoneNumber;
            detailCart.OrderHeader.PickUpTime = DateTime.Now;

            if (HttpContext.Session.GetString (SD.ssCouponCode) != null) {
                detailCart.OrderHeader.CouponCode = HttpContext.Session.GetString (SD.ssCouponCode);
                var couponFromDb = await _db.Coupon.Where (c => c.Name.ToLower () == detailCart.OrderHeader.CouponCode.ToLower ()).FirstOrDefaultAsync ();
                detailCart.OrderHeader.OrderTotal = SD.DiscountedPrice (couponFromDb, detailCart.OrderHeader.OrderTotalOriginal);
            }

            return View (detailCart);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName ("Summary")]
        public async Task<IActionResult> SummaryPost (string stripeToken) {
            var claimsIdentity = (ClaimsIdentity) User.Identity;
            var claim = claimsIdentity.FindFirst (ClaimTypes.NameIdentifier);

            detailCart.listCart = await _db.ShoppingCart.Where (c => c.ApplicationUserId == claim.Value).ToListAsync ();

            detailCart.OrderHeader.PaymentStatus = SD.PaymentStatusPending;
            detailCart.OrderHeader.OrderDate = DateTime.Now;
            detailCart.OrderHeader.UserId = claim.Value;
            detailCart.OrderHeader.Status = SD.PaymentStatusPending;
            detailCart.OrderHeader.PickUpTime = Convert.ToDateTime (detailCart.OrderHeader.PickUpDate.ToShortDateString () + " " + detailCart.OrderHeader.PickUpTime.ToShortTimeString ());

            List<OrderDetails> orderDetailsList = new List<OrderDetails> ();
            _db.OrderHeader.Add (detailCart.OrderHeader);
            await _db.SaveChangesAsync ();

            detailCart.OrderHeader.OrderTotalOriginal = 0;

            foreach (var item in detailCart.listCart) {
                item.MenuItem = await _db.MenuItem.FirstOrDefaultAsync (m => m.Id == item.MenuItemId);
                OrderDetails orderDetails = new OrderDetails {
                    MenuItemId = item.MenuItemId,
                    OrderId = detailCart.OrderHeader.Id,
                    Description = item.MenuItem.Description,
                    Name = item.MenuItem.Name,
                    Price = item.MenuItem.Price,
                    Count = item.Count
                };
                detailCart.OrderHeader.OrderTotalOriginal += orderDetails.Count * orderDetails.Price;
                _db.OrderDetails.Add (orderDetails);

            }

            if (HttpContext.Session.GetString (SD.ssCouponCode) != null) {
                detailCart.OrderHeader.CouponCode = HttpContext.Session.GetString (SD.ssCouponCode);
                var couponFromDb = await _db.Coupon.Where (c => c.Name.ToLower () == detailCart.OrderHeader.CouponCode.ToLower ()).FirstOrDefaultAsync ();
                detailCart.OrderHeader.OrderTotal = SD.DiscountedPrice (couponFromDb, detailCart.OrderHeader.OrderTotalOriginal);
            } else {
                detailCart.OrderHeader.OrderTotal = detailCart.OrderHeader.OrderTotalOriginal;
            }
            detailCart.OrderHeader.CouponCodeDiscount = detailCart.OrderHeader.OrderTotalOriginal - detailCart.OrderHeader.OrderTotal;

            _db.ShoppingCart.RemoveRange (detailCart.listCart);
            HttpContext.Session.SetInt32 (SD.ssShoppingCartCount, 0);
            await _db.SaveChangesAsync ();

            detailCart.OrderHeader.TransactionId = "txn_" + RandomString(24);

            detailCart.OrderHeader.PaymentStatus = SD.PaymentStatusApproved;
            detailCart.OrderHeader.Status = SD.StatusSubmitted;

            await _db.SaveChangesAsync ();
            return RedirectToAction ("Index", "Home");

        }

        public IActionResult AddCoupon () {
            if (detailCart.OrderHeader.CouponCode == null) {
                detailCart.OrderHeader.CouponCode = "";
            }
            HttpContext.Session.SetString (SD.ssCouponCode, detailCart.OrderHeader.CouponCode);

            return RedirectToAction (nameof (Index));
        }

        public IActionResult RemoveCoupon () {

            HttpContext.Session.SetString (SD.ssCouponCode, string.Empty);

            return RedirectToAction (nameof (Index));
        }

        public async Task<IActionResult> Plus (int cartId) {
            var cart = await _db.ShoppingCart.FirstOrDefaultAsync (c => c.Id == cartId);
            cart.Count += 1;
            await _db.SaveChangesAsync ();
            return RedirectToAction (nameof (Index));
        }

        public async Task<IActionResult> Minus (int cartId) {
            var cart = await _db.ShoppingCart.FirstOrDefaultAsync (c => c.Id == cartId);
            if (cart.Count == 1) {
                _db.ShoppingCart.Remove (cart);
                await _db.SaveChangesAsync ();

                var cnt = _db.ShoppingCart.Where (u => u.ApplicationUserId == cart.ApplicationUserId).ToList ().Count;
                HttpContext.Session.SetInt32 (SD.ssShoppingCartCount, cnt);
            } else {
                cart.Count -= 1;
                await _db.SaveChangesAsync ();
            }

            return RedirectToAction (nameof (Index));
        }

        public async Task<IActionResult> Remove (int cartId) {
            var cart = await _db.ShoppingCart.FirstOrDefaultAsync (c => c.Id == cartId);

            _db.ShoppingCart.Remove (cart);
            await _db.SaveChangesAsync ();

            var cnt = _db.ShoppingCart.Where (u => u.ApplicationUserId == cart.ApplicationUserId).ToList ().Count;
            HttpContext.Session.SetInt32 (SD.ssShoppingCartCount, cnt);

            return RedirectToAction (nameof (Index));
        }

    }
}

Spice/Areas/Customer/Views/Cart/Index.cshtml
@model Spice.Models.ViewModels.OrderDetailsCart

@{
    ViewData["Title"] = "Giỏ hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post">
    @if (Model.listCart.Count > 0)
    {
        <br />
        <input id="userId" asp-for="@Model.listCart[0].ApplicationUserId" hidden />
        <div class="backgroundWhiteBorder">
            <div class="container">
                <div class="card">
                    <div class="card-header bg-dark text-light ml-0 row container">
                        <div class="col-6">
                            <i class="fa fa-shopping-cart"></i> &nbsp;
                            Giỏ hàng
                        </div>
                        <div class="col-6 text-right">
                            <a asp-area="Customer" asp-controller="Home" asp-action="Index" class="btn btn-outline-info btn-sm">Tiếp tục mua sắm</a>
                        </div>
                    </div>
                    <div class="card-body">
                        @foreach (var item in Model.listCart)
                        {
                            <div class="row">
                                <div class="d-none d-lg-block col-lg-2 text-center py-2">
                                    <img src="@item.MenuItem.Image" class="rounded" width="120" height="80" />
                                </div>
                                <div class="col-12 text-sm-center col-lg-5 text-lg-left">
                                    <h4><strong>@item.MenuItem.Name</strong></h4>
                                    <h4><small>@item.MenuItem.Description</small></h4>
                                </div>
                                <div class="col-12 text-sm-center col-lg-5 text-lg-right row">
                                    <div class="col-4 text-md-right" style="padding-top:5px;">
                                        <h6><strong>@item.MenuItem.Price vnđ <span class="text-muted">x</span> @item.Count </strong></h6>
                                    </div>
                                    <div class="col-6 col-sm-4 col-lg-6">
                                        <div class="float-right mx-1">
                                            <button type="submit" class="btn btn-primary" asp-action="plus" asp-route-cartId="@item.Id">
                                                <i class="fas fa-plus"></i>
                                            </button>
                                        </div>
                                        <div class="float-right mx-1">
                                            <button type="submit" class="btn btn-danger" asp-action="minus" asp-route-cartId="@item.Id">
                                                <i class="fas fa-minus"></i>
                                            </button>
                                        </div>
                                    </div>
                                    <div class="col-2 col-sm-4 col-lg-2 text-right">
                                        <button type="submit" class="btn btn-outline-danger" asp-action="remove" asp-route-cartId="@item.Id">
                                            <i class="fas fa-trash"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                            <hr />
                        }

                        <div class="row">
                            <div class="col-12 col-md-5">
                                <div class="row">
                                    <div class="col-7">
                                        <input asp-for="@Model.OrderHeader.CouponCode" id="txtCouponCode" class="form-control" placeholder="nhập mã giảm giá..." />
                                    </div>
                                    <div class="col-5" style="margin-top:2px;">
                                        <button type="submit" class="btn btn-sm form-control btn-outline-success" id="btnCoupon" asp-action="AddCoupon">
                                            Áp dụng
                                        </button>
                                        <button type="submit" class="btn btn-sm form-control btn-outline-danger" style="display:none" id="btnRemoveCoupon" asp-action="RemoveCoupon">
                                            Xóa
                                        </button>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-md-6 offset-md-1 col-lg-4 offset-lg-3 pr-4">
                                <ul class="list-group">
                                    <li class="list-group-item d-flex justify-content-between bg-light">
                                        <span class="text-info"> Tổng cộng</span>
                                        <strong class="text-info">VNĐ <span id="txtOrderTotal">@Model.OrderHeader.OrderTotal</span></strong>
                                    </li>
                                </ul>
                            </div>
                        </div>

                    </div>
                    <div class="card-footer">
                        <div class="col-12 col-lg-4 offset-lg-8 col-md-6 offset-md-6">
                            <a asp-action="Summary" asp-area="Customer" asp-controller="Cart" class="btn btn-success form-control">Thông tin vận chuyển</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
    else
    {
        <div class="backgroundWhiteBorder"> Không có gì ở đây...</div>
    }
</form>

@section Scripts{ 
    <script>
        $(function () {
            var couponCode = document.getElementById("txtCouponCode").value;

            if (couponCode.length > 0) {
                document.getElementById('btnCoupon').style.display = 'none';
                document.getElementById('btnRemoveCoupon').style.display = '';
            }
            else {
                document.getElementById('btnCoupon').style.display = '';
                document.getElementById('btnRemoveCoupon').style.display = 'none';
            }
        });
    </script>
}

Spice/Areas/Customer/Views/Cart/Summary.cshtml
@model Spice.Models.ViewModels.OrderDetailsCart
@using Microsoft.Extensions.Options

@{
    ViewData["Title"] = "Chi tiết";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post">
    @if (Model.listCart.Count > 0)
    {
        <br />
        <input id="userId" asp-for="@Model.listCart[0].ApplicationUserId" hidden />
        <div class="backgroundWhiteBorder">
            <div class="container">
                <div class="card">
                    <div class="card-header bg-dark text-light ml-0 row container">
                        <div class="col-6">
                            <i class="fa fa-shopping-cart"></i> &nbsp;
                            Thông tin vận chuyển
                        </div>
                        <div class="col-6 text-right">
                            <a asp-area="Customer" asp-controller="Cart" asp-action="Index" class="btn btn-outline-info btn-sm">Quay lại giỏ hàng</a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="container rounded p-2">
                            <div class="row">
                                <div class="col-12 col-lg-6 pb-4">
                                    <div class="row">
                                        <h4 class="d-flex justify-content-between align-items-center mb-3">
                                            <span class="text-info">Thông tin người nhận:</span>
                                        </h4>
                                    </div>
                                    <div class="row my-1">
                                        <div class="col-3">
                                            <label>Tên</label>
                                        </div>
                                        <div class="col-9">
                                            <input asp-for="@Model.OrderHeader.PickupName" id="txtName" type="text" class="form-control" />
                                        </div>
                                    </div>
                                    <div class="row my-1">
                                        <div class="col-3">
                                            <label>Số điện thoại</label>
                                        </div>
                                        <div class="col-9">
                                            <input asp-for="@Model.OrderHeader.PhoneNumber" id="txtPhone" type="text" class="form-control" />
                                        </div>
                                    </div>
                                    <div class="row my-1">
                                        <div class="col-3">
                                            <label>Ngày</label>
                                        </div>
                                        <div class="col-9">
                                            <input asp-for="@Model.OrderHeader.PickUpDate" id="datepicker" value="" type="text" class="form-control" />
                                        </div>
                                    </div>
                                    <div class="row my-1">
                                        <div class="col-3">
                                            <label>Thời gian</label>
                                        </div>
                                        <div class="col-9">
                                            <input asp-for="@Model.OrderHeader.PickUpTime" id="timepicker" value="" type="text" class="form-control" />
                                        </div>
                                    </div>
                                    <div class="row my-1">
                                        <div class="col-3">
                                            <label>Lời nhắn: </label>
                                        </div>
                                        <div class="col-9">
                                            <textarea asp-for="@Model.OrderHeader.Comments" style="height:100px;" class="form-control"></textarea>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-12 col-lg-5 offset-lg-1">
                                        <h4 class="d-flex justify-content-between align-items-center mb-3">
                                            <span class="text-info">Chi tiết đơn hàng:</span>
                                        </h4>
                                        <ul class="list-group mb-3">
                                            @{ var total = 0.0;}

                                            @foreach (var details in Model.listCart)
                                            {
                                                <li class="list-group-item d-flex justify-content-between">
                                                    <div>
                                                        <h6 class="my-0">@details.MenuItem.Name</h6>
                                                        <small class="text-muted">Số lượng: @details.Count</small>
                                                    </div>
                                                    <span class="text-muted">@(details.MenuItem.Price * details.Count) vnđ</span>
                                                    @{ total += (details.MenuItem.Price * details.Count); }
                                                </li>
                                            }
                                            @if (Model.OrderHeader.CouponCode != null)
                                            {
                                                <li class="list-group-item d-flex justify-content-between">
                                                    <div class="text-success">
                                                        <h6 class="my-0">Mã giảm giá</h6>
                                                        <small class="text-success">@Model.OrderHeader.CouponCode</small>
                                                    </div>
                                                    <span class="text-success">-@(total - Model.OrderHeader.OrderTotal) vnđ</span>
                                                </li>
                                            }
                                            <li class="list-group-item d-flex justify-content-between bg-light">
                                                    <small class="text-info">Tổng cộng</small>
                                                <strong class="text-info">VNĐ @(Model.OrderHeader.OrderTotal)</strong>
                                            </li>
                                        </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <div class="col-12 col-md-4 offset-md-8">
                                @{
                                    var OrderTotalForStrip = Model.OrderHeader.OrderTotal * 100;
                                }
                                <script>
                                    document.getElementsByClassName("stripe-button-el")[0].style.display = 'none';
                                </script>
                                <button type="submit" id="btnPlaceOrder" onclick="return validateInput()" value="Place Order" class="btn btn-success form-control">Đặt hàng</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
    else
    {
        <div class="backgroundWhiteBorder">Không có gì ở đây...</div>
    }
</form>

@section Scripts{

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.js"></script>

    <script>
        $(function () {
            var minDt = 0;
            if (getTimeFromCurrentDate() >= "20.00") {
                minDt = 1;
            }
            $("#datepicker").datepicker({ minDate: minDt, maxDate: "+1W" });
            $("#timepicker").timepicker({'minTime': '11:00 AM', 'maxTime': '9:00 PM', step: '30'})
        });

        function setPickUpTime() {
            var dateSelected = document.getElementById("datepicker").value;
            var dt = new Date(dateSelected);
            var today = new Date();
            dt.setHours(0, 0, 0, 0);
            if (dt > today) {
                selectedTime = '11:00am';
            }
            else {
                selectedTime = getTimeFromCurrentDate();
            }
            $('#timepicker').timepicker('option', 'minTime', selectedTime);
        }

        function getTimeFromCurrentDate() {
            var curDt = new Date();

            var minTime = "";
            if (curDt.getHours() < 11) {
                minTime = '12:00pm';
            }
            else {
                if (curDt.getMinutes() < 30) {
                    minTime = (curDt.getHours() + 1).toString() + ':30pm'
                }
                else {
                    minTime = (curDt.getHours() + 2).toString() + ':00pm'
                }
            }
            return minTime;
        }

        $('#datepicker').change(function () {
            setPickUpTime();
        });


        function validateInput() {
            var time = document.getElementById("timepicker").value;
            var dt = document.getElementById("datepicker").value;
            var name = document.getElementById("txtName").value;
            var phone = document.getElementById("txtPhone").value;
            if (dt.toString().length == 0) {
                alert("Please select pickup date")
                return false;
            }
            else if (time.toString().length == 0) {
                alert("Please select pickup time")
                return false;
            }
            else if (name.toString().length == 0) {
                alert("Please enter pickup name")
                return false;
            }
            else if (phone.toString().length == 0) {
                alert("Please enter a phone number")
                return false;
            }
            else {
                return true;
            }
        }

    </script>
}