Spice/Areas/Admin/Controllers/CouponController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Spice.Data;
using Spice.Models;
using Spice.Utility;

namespace Spice.Areas.Admin.Controllers {
    [Area ("Admin")]
    [Authorize (Roles = SD.ManagerUser)]
    public class CouponController : Controller {
        private readonly ApplicationDbContext _db;

        public CouponController (ApplicationDbContext db) {
            _db = db;
        }

        public async Task<IActionResult> Index () {
            return View (await _db.Coupon.ToListAsync ());
        }

        public IActionResult Create () {
            return View ();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create (Coupon coupons) {
            if (ModelState.IsValid) {
                var files = HttpContext.Request.Form.Files;
                if (files.Count > 0) {
                    byte[] p1 = null;
                    using (var fs1 = files[0].OpenReadStream ()) {
                        using (var ms1 = new MemoryStream ()) {
                            fs1.CopyTo (ms1);
                            p1 = ms1.ToArray ();
                        }
                    }
                    coupons.Picture = p1;
                }
                _db.Coupon.Add (coupons);
                await _db.SaveChangesAsync ();
                return RedirectToAction (nameof (Index));
            }
            return View (coupons);
        }

        //GET Edit Coupon
        public async Task<IActionResult> Edit (int? id) {
            if (id == null) {
                return NotFound ();
            }
            var coupon = await _db.Coupon.SingleOrDefaultAsync (m => m.Id == id);
            if (coupon == null) {
                return NotFound ();
            }
            return View (coupon);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit (Coupon coupons) {
            if (coupons.Id == 0) {
                return NotFound ();
            }

            var couponFromDb = await _db.Coupon.Where (c => c.Id == coupons.Id).FirstOrDefaultAsync ();

            if (ModelState.IsValid) {
                var files = HttpContext.Request.Form.Files;
                if (files.Count > 0) {
                    byte[] p1 = null;
                    using (var fs1 = files[0].OpenReadStream ()) {
                        using (var ms1 = new MemoryStream ()) {
                            fs1.CopyTo (ms1);
                            p1 = ms1.ToArray ();
                        }
                    }
                    couponFromDb.Picture = p1;
                }
                couponFromDb.MinimumAmount = coupons.MinimumAmount;
                couponFromDb.Name = coupons.Name;
                couponFromDb.Discount = coupons.Discount;
                couponFromDb.CouponType = coupons.CouponType;
                couponFromDb.IsActive = coupons.IsActive;

                await _db.SaveChangesAsync ();
                return RedirectToAction (nameof (Index));
            }
            return View (coupons);
        }

        public async Task<IActionResult> Details (int? id) {
            if (id == null) {
                return NotFound ();
            }

            var coupon = await _db.Coupon
                .FirstOrDefaultAsync (m => m.Id == id);
            if (coupon == null) {
                return NotFound ();
            }

            return View (coupon);
        }

        //GET Delete Coupon
        public async Task<IActionResult> Delete (int? id) {
            if (id == null) {
                return NotFound ();
            }
            var coupon = await _db.Coupon.SingleOrDefaultAsync (m => m.Id == id);
            if (coupon == null) {
                return NotFound ();
            }
            return View (coupon);
        }

        [HttpPost, ActionName ("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed (int id) {
            var coupons = await _db.Coupon.SingleOrDefaultAsync (m => m.Id == id);
            _db.Coupon.Remove (coupons);
            await _db.SaveChangesAsync ();
            return RedirectToAction (nameof (Index));
        }
    }
}

Spice/Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Spice.Data;
using Spice.Utility;

namespace Spice.Areas.Admin.Controllers {
    [Area ("Admin")]
    [Authorize (Roles = SD.ManagerUser)]
    public class UserController : Controller {
        private readonly ApplicationDbContext _db;

        public UserController (ApplicationDbContext db) {
            _db = db;
        }

        public async Task<IActionResult> Index () {
            var claimsIdentity = (ClaimsIdentity) this.User.Identity;
            var claim = claimsIdentity.FindFirst (ClaimTypes.NameIdentifier);

            return View (await _db.ApplicationUser.Where (u => u.Id != claim.Value).ToListAsync ());
        }

        public async Task<IActionResult> Lock (string id) {
            if (id == null) {
                return NotFound ();
            }

            var applicationUser = await _db.ApplicationUser.FirstOrDefaultAsync (m => m.Id == id);

            if (applicationUser == null) {
                return NotFound ();
            }

            applicationUser.LockoutEnd = DateTime.Now.AddYears (1000);

            await _db.SaveChangesAsync ();

            return RedirectToAction (nameof (Index));
        }

        public async Task<IActionResult> UnLock (string id) {
            if (id == null) {
                return NotFound ();
            }

            var applicationUser = await _db.ApplicationUser.FirstOrDefaultAsync (m => m.Id == id);

            if (applicationUser == null) {
                return NotFound ();
            }

            applicationUser.LockoutEnd = DateTime.Now;

            await _db.SaveChangesAsync ();

            return RedirectToAction (nameof (Index));
        }
    }
}

Spice/Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-info form-control" value="Tạo" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Quay lại</a>
    </div>
</div>

Spice/Views/Shared/_CreateButtonPartial.cshtml
<p>
    <a asp-action="Create" class="btn btn-info"><i class="fas fa-plus"></i> &nbsp;  Tạo mới </a>
</p>

Spice/Views/Shared/_DeleteAndBackToListButton.cshtml
@model int

<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-danger form-control" asp-route-id="@Model" value="Xóa" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Quay lại</a>
    </div>
</div>

Spice/Views/Shared/_DetailsAndBackToListButton.cshtml
@model int

<div class="row">
    <div class="col-6">
        <a asp-action="Edit" asp-route-id="@Model" class="btn btn-info form-control">Chỉnh sửa</a>
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Quay lại</a>
    </div>
</div>

Spice/Views/Shared/_EditAndBackToListButton.cshtml
@model int  

<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-info form-control" asp-route-id="@Model" value="Cập nhật" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Quay lại</a>
    </div>
</div>

Spice/Views/Shared/_IndividualOrderDetails.cshtml
@model Spice.Models.ViewModels.OrderDetailsViewModel
@using Spice.Utility
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<form asp-action="OrderPickup" asp-controller="Order" asp-route-orderId="@Model.OrderHeader.Id" method="post">
    <div class="container row border ml-1 backgroundWhiteBorder10Padding" style="width:100%">
        <div class="col-lg-8 col-12" style="border-right:1px solid #bbb9b9">
            <br />
            <input type="hidden" asp-for="OrderHeader.Id" />

            <div class="form-group row">
                <div class="col-3">
                    <label>Tên</label>
                </div>
                <div class="col-9">
                    <input asp-for="OrderHeader.PickupName" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label asp-for="OrderHeader.ApplicationUser.Email"></label>
                </div>
                <div class="col-9">
                    <input asp-for="OrderHeader.ApplicationUser.Email" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label asp-for="OrderHeader.ApplicationUser.PhoneNumber"></label>
                </div>
                <div class="col-9">
                    <input asp-for="OrderHeader.ApplicationUser.PhoneNumber" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label asp-for="OrderHeader.OrderTotal"></label>
                </div>
                <div class="col-9">
                    <input asp-for="OrderHeader.OrderTotal" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label asp-for="OrderHeader.PickUpTime"></label>
                </div>
                <div class="col-9">
                    <input value="@Model.OrderHeader.PickUpTime.ToShortDateString() @Model.OrderHeader.PickUpTime.ToShortTimeString()" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label asp-for="OrderHeader.Comments"></label>
                </div>
                <div class="col-9">
                    <input asp-for="OrderHeader.Comments" disabled class="form-control" />
                </div>
            </div>
        </div>



        <div class="col-lg-4 col-12">
            <h4 class="d-flex justify-content-between align-content-center mb-3">
                <span class="text-muted">Mã đơn hàng: </span>
                <span class="badge badge-secondary badge-pill">@Model.OrderHeader.Id</span>
            </h4>
            <ul class="list-group mb-3">
                @foreach (var details in Model.OrderDetails)
                {
                    <li class="list-group-item d-flex justify-content-between">
                        <div>
                            <h6 class="my-0">@details.Name</h6>
                            <small class="text-muted">Số lượng : @details.Count</small>
                        </div>
                        <span class="text-muted">@(details.Price * details.Count)</span>
                    </li>
                }
                @if (Model.OrderHeader.CouponCode != null)
                {
                    <li class="list-group-item d-flex justify-content-between">
                        <div class="text-success">
                            <h6 class="my-0">Mã giảm giá</h6>
                            <small>@Model.OrderHeader.CouponCode</small>
                        </div>
                        <span class="text-success">@(Model.OrderHeader.OrderTotalOriginal - Model.OrderHeader.OrderTotal)</span>
                    </li>
                }
                <li class="list-group-item d-flex justify-content-between bg-light">
                    <span class="text-info"> Tổng cộng</span>
                    <strong class="text-info">VNĐ @Model.OrderHeader.OrderTotal</strong>
                </li>

            </ul>
            @if (Model.OrderHeader.Status.Equals(SD.StatusReady) && (User.IsInRole(SD.ManagerUser) || User.IsInRole(SD.FrontDeskUser)))
            {
                <button type="submit"  class="btn btn-success form-control"><i class="far fa-thumbs-up"></i> Xác nhận</button>
            }
            else
            { 
                <button type="submit" disabled class="btn btn-info form-control">@Model.OrderHeader.Status</button>
            }
        </div>

    </div>
</form>

Spice/Views/Shared/_Layout.cshtml
@using Spice.Utility
@using Microsoft.AspNetCore.Http

@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cay Cú</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/jquery-ui.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
        <link rel="stylesheet" href="~/css/jquery-ui.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="search-background">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">
                    @*<img src="~/images/mild.png" />
                    <img src="~/images/spicy.png" />
                    <img src="~/images/verySpicy.png" />*@
                    <label class="text-white font-weight-bold" style="cursor:pointer">Cay Cú 🔥</label>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole(SD.ManagerUser))
                        {
                            <li class="nav-item dropdown text-white-50">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropDownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Quản lý
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropDownMenuLink">
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Category" asp-area="Admin">Nhóm</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="SubCategory" asp-area="Admin">Danh mục</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="MenuItem" asp-area="Admin">Sản phẩm</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Coupon" asp-area="Admin">Mã giảm giá</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="User" asp-area="Admin">Người dùng</a>
                                </div>
                            </li>
                        }
                        @if (User.IsInRole(SD.ManagerUser) || User.IsInRole(SD.CustomerEndUser) || User.IsInRole(SD.FrontDeskUser) || User.IsInRole(SD.KitchenUser) )
                        {
                            <li class="nav-item">
                                <a asp-area="Customer" asp-controller="Order" asp-action="OrderHistory" class="nav-link">
                                    Lịch sử giao dịch
                                </a>
                            </li>
                        }

                        @if (User.IsInRole(SD.FrontDeskUser) || User.IsInRole(SD.KitchenUser) || User.IsInRole(SD.ManagerUser))
                        {
                            <li class="nav-item dropdown text-white-50">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Đơn hàng
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropDownMenuLink">
                                    @if (User.IsInRole(SD.KitchenUser) || User.IsInRole(SD.ManagerUser))
                                    {
                                        <a class="dropdown-item" asp-action="ManageOrder" asp-controller="Order" asp-area="Customer">Quản lý đơn hàng</a>
                                    }
                                    @if (User.IsInRole(SD.FrontDeskUser) || User.IsInRole(SD.ManagerUser))
                                    {
                                        <a class="dropdown-item" asp-action="OrderPickup" asp-controller="Order" asp-area="Customer">Đơn hàng đã nhận</a>
                                    }
                                    </div>

                            </li>
                        }

                        @if (HttpContextAccessor.HttpContext.Session.GetInt32(@SD.ssShoppingCartCount) != null)
                        {
                            <li style="color:white">
                                <a asp-area="Customer" asp-controller="Cart" asp-action="Index" class="nav-link">
                                    @{
                                        var count = HttpContextAccessor.HttpContext.Session.GetInt32(@SD.ssShoppingCartCount);
                                    }
                                    <i class="fas fa-shopping-cart"></i> &nbsp; (@count)
                                </a>
                            </li>
                        }
                        else
                        {
                            <li style="color:white">
                                <a href="#" class="nav-link">
                                    <i class="fas fa-shopping-cart"></i> &nbsp; (0)
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <environment include="Development">
        <script src="https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=n94ifuzvl80pchikopiwgz2esrw8n28dwcywvpejlqrregfp"></script>
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="~/js/jquery-ui.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=n94ifuzvl80pchikopiwgz2esrw8n28dwcywvpejlqrregfp"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
        <script src="~/js/jquery-ui.js"></script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Spice/Views/Shared/_OrderStatus.cshtml
@model string
@using Spice.Utility
<div style="width:100%">
    @if (Model == SD.StatusSubmitted)
    {
        <img src="~/images/OrderPlaced.png" width="100%" />
    }
    @if (Model == SD.StatusInProcess)
    {
        <img src="~/images/InKitchen.png" width="100%" />
    }
    @if (Model == SD.StatusReady)
    {
        <img src="~/images/ReadyForPickup.png" width="100%" />
    }
    @if (Model == SD.StatusCompleted)
    {
        <img src="~/images/completed.png" width="100%" />
    }
</div>

Spice/Views/Shared/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}

Spice/Views/Shared/_TableButtonPartial.cshtml
@model int  

<td style="width:150px">
    <div class="btn-group" role="group">
        <a class="btn btn-primary text-white" asp-action="Edit" asp-route-Id="@Model">
            <i class="fas fa-edit"></i>
        </a>

        <a class="btn btn-success text-white" asp-action="Details" asp-route-Id="@Model">
            <i class="fas fa-list-alt"></i>
        </a>

        <a class="btn btn-danger text-white" asp-action="Delete" asp-route-Id="@Model">
            <i class="fas fa-trash-alt"></i>
        </a>
    </div>
</td>

Spice/Views/Shared/_ThumbnailAreaPArtial.cshtml
@model IEnumerable<MenuItem>
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

@if (Model.Count() > 0)
{
    <div class="col-12 post @Model.FirstOrDefault().Category.Name.Replace(" ",string.Empty) menu-restaurant">
        <div class="row">
            <h3 class="text-success"> @Model.FirstOrDefault().Category.Name </h3>
        </div>

        @foreach(var item in Model)
        {
            <div class="border border-info rounded col-12" style="margin-bottom:10px; margin-top:10px; padding:10px">
                <div class="row">
                    <div class="col-md-3 col-sm-12">
                        <a asp-action="Details" asp-route-id="@item.Id">
                            <img src="@item.Image" width="99%" style="border-radius:5px;border:1px solid #bbb9b9" />
                        </a>
                    </div>
                    <div class="col-md-9 col-sm-12">
                        <div class="row pr-3">
                            <div class="col-8">
                                <a asp-action="Details" asp-route-id="@item.Id">
                                    <label class="text-primary" style="font-size:21px;color:maroon">@item.Name</label>
                                </a>
                                @if (item.Spicyness == "1")
                                {
                                    <img srcset="/images/mild.png" title="Ít cay" />
                                }
                                @if (item.Spicyness == "2")
                                {
                                    <img srcset="/images/spicy.png" title="Cay" />
                                }
                                @if (item.Spicyness == "3")
                                {
                                    <img srcset="/images/veryspicy.png" title="Cay lắm" />
                                }
                            </div>
                            <div class="col-4 text-right" style="color:maroon">
                                <h4>@item.Price đ</h4>
                            </div>
                        </div>


                        <div class="row col-12 text-justify d-none d-md-block">
                            <p>@Html.Raw(item.Description)</p>
                        </div>
                        <div class="col-md-3 col-sm-12 offset-md-9 text-center">
                            <a asp-action="Details" class="btn btn-success form-control" asp-route-id="@item.Id">Chi tiết</a>
                        </div>
                    </div>
                    </div>
                </div> 
        }
        <div class="p-4"></div>
    </div>
}